resources:
  - clusterissuer.yaml

replacements:
  - source:
      kind: Secret
      name: acme-email
      fieldPath: data.email
    targets:
      - select:
          kind: ClusterIssuer
          name: letsencrypt-dns
        fieldPaths:
          - spec.acme.email
        options:
          delimiter: ""
          encoding: base64
