resources:
  - clusterissuer.yaml

vars:
  - name: ACME_EMAIL
    objref:
      kind: Secret
      name: acme-email
      namespace: cert-manager
      apiVersion: v1
    fieldref:
      fieldpath: data.email
