apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: auth-provider

images:
  - name: docker-registry.kuroweb.net/auth-provider-backend:placeholder
    newName: docker-registry.kuroweb.net/auth-provider-backend-production
    newTag: placeholder
