#
# Service
#

apiVersion: v1
kind: Service
metadata:
  name: backend-batch-service
  namespace: price-monitoring
spec:
  selector:
    app: price-monitoring
    server: backend-batch
  type: LoadBalancer
  ports:
    - name: backend-db-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  loadBalancerIP: 192.168.0.211

---
#
# Deployment
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-batch-deployment
  namespace: price-monitoring
  labels:
    app: price-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-monitoring
      server: backend-batch
  template:
    metadata:
      labels:
        app: price-monitoring
        server: backend-batch
    spec:
      containers:
        - name: backend-batch
          image: registry.local:5000/price-monitoring-backend:latest
          command: ["sidekiq", "-C", "config/sidekiq.yml", "-e", "production"]
          ports:
            - name: backend-db-port
              containerPort: 3000
          env:
            - name: DB_HOST_NAME
              value: 192.168.0.212
            - name: DB_DATABASE_NAME
              value: rails
            - name: DB_USER_NAME
              value: root
            - name: DB_PASSWORD
              value: ""
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-master-key
                  key: RAILS_MASTER_KEY
