#
# Service
#

apiVersion: v1
kind: Service
metadata:
  name: backend-batch-service
  namespace: price-monitoring
spec:
  selector:
    app: price-monitoring
    server: backend-batch
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  loadBalancerIP: 192.168.0.211

---
#
# Deployment
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-batch-deployment
  namespace: price-monitoring
  labels:
    app: price-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: price-monitoring
      server: backend-batch
  template:
    metadata:
      labels:
        app: price-monitoring
        server: backend-batch
    spec:
      containers:
        - name: backend-batch
          image: registry.local:5000/price-monitoring-backend:a7a7b14a70da8116e9e815c9cd745602fbb75da2
          command: ["sidekiq", "-C", "config/sidekiq.yml", "-e", "production"]
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: DB_HOST_NAME
              value: 192.168.0.212
            - name: DB_DATABASE_NAME
              value: rails
            - name: DB_USER_NAME
              value: root
            - name: DB_PASSWORD
              value: ""
            - name: REDIS_URL
              value: "redis://192.168.0.213:6379"
            - name: TOR_URL
              value: "socks5://192.168.0.214:9050"
            - name: PLAYWRIGHT_URL
              value: "ws://192.168.0.215:8888/ws"
            - name: ALLOWED_ORIGIN
              value: "192.168.0.211"
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: rails-master-key
                  key: RAILS_MASTER_KEY
