#
# Service
#

apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: price-monitoring
spec:
  selector:
    app: price-monitoring
    server: bff
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  loadBalancerIP: 192.168.0.216

---
#
# Deployment
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
  namespace: price-monitoring
  labels:
    app: price-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-monitoring
      server: bff
  template:
    metadata:
      labels:
        app: price-monitoring
        server: bff
    spec:
      containers:
        - name: bff
          image: registry.local:5000/price-monitoring-bff:9e0bd6043f88f3d9967c5d6c155e66adc22fc4bc
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: ALLOWED_ORIGIN
              value: "192.168.0.216"
            - name: BACKEND_URL
              value: "http://192.168.0.210:3000"
