apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: price-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: ddns
          image: favonia/cloudflare-ddns:latest
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token
                  key: api-token
            - name: DOMAINS
              value: price-monitoring.kuroweb.net
            - name: PROXIED
              value: "false"
            - name: UPDATE_ON_START
              value: "true"
            - name: IP6_PROVIDER
              value: "none"
      restartPolicy: Always
