apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-script
  namespace: price-monitoring
data:
  update.sh: |
    #!/bin/sh
    set -e

    CF_API_TOKEN="$CF_API_TOKEN"
    ZONE_NAME="kuroweb.net"
    RECORD_NAME="kuroweb.net"
    IP=$(curl -s https://api.ipify.org)

    ZONE_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=${ZONE_NAME}" \
      -H "Authorization: Bearer ${CF_API_TOKEN}" \
      -H "Content-Type: application/json" | jq -r '.result[0].id')

    RECORD_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?name=${RECORD_NAME}" \
      -H "Authorization: Bearer ${CF_API_TOKEN}" \
      -H "Content-Type: application/json" | jq -r '.result[0].id')

    curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${RECORD_ID}" \
      -H "Authorization: Bearer ${CF_API_TOKEN}" \
      -H "Content-Type: application/json" \
      --data "{\"type\":\"A\",\"name\":\"${RECORD_NAME}\",\"content\":\"${IP}\",\"ttl\":300,\"proxied\":false}"
