apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db-deployment
  namespace: price-monitoring
  labels:
    app: price-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-monitoring
      server: backend-db
  template:
    metadata:
      labels:
        app: price-monitoring
        server: backend-db
    spec:
      containers:
        - name: backend-db
          image: mysql/mysql-server:8.0
          ports:
            - name: backend-db-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
