apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db-pvc
  namespace: price-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
