apiVersion: v1
kind: Service
metadata:
  name: backend-batch-service
  namespace: price-monitoring
spec:
  selector:
    app: price-monitoring
    server: backend-batch
  type: LoadBalancer
  ports:
    - name: backend-db-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  loadBalancerIP: 192.168.0.211
