apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: price-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kuroweb/k8s.git
    targetRevision: HEAD
    path: manifests/price-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: price-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
