apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: price-monitoring-integration

images:
  - name: docker-registry.kuroweb.net/price-monitoring-backend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-integration
    newTag: 8b21566b1cd7f4a1be8479f0ffcb6ce2d1b8ad1f
  - name: docker-registry.kuroweb.net/price-monitoring-backend-playwright:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-playwright-integration
    newTag: 8b21566b1cd7f4a1be8479f0ffcb6ce2d1b8ad1f
  - name: docker-registry.kuroweb.net/price-monitoring-frontend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-frontend-integration
    newTag: 8b21566b1cd7f4a1be8479f0ffcb6ce2d1b8ad1f

patches:
  - path: patches/backend.yaml
  - path: patches/backend-db.yaml
  - path: patches/backend-redis.yaml
  - path: patches/backend-playwright.yaml
  - path: patches/backend-migrate.yaml
  - path: patches/backend-batch-1.yaml
  - path: patches/backend-batch-2.yaml
  - path: patches/backend-batch-3.yaml
  - path: patches/backend-batch-4.yaml
  - path: patches/frontend.yaml
  - path: patches/web-ingress.yaml
