apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: price-monitoring-production

images:
  - name: docker-registry.kuroweb.net/price-monitoring-backend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-production
    newTag: 444e650fe3fc3b22529a775d1594ae2dd819278b
  - name: docker-registry.kuroweb.net/price-monitoring-backend-playwright:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-playwright-production
    newTag: 444e650fe3fc3b22529a775d1594ae2dd819278b
  - name: docker-registry.kuroweb.net/price-monitoring-frontend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-frontend-production
    newTag: 444e650fe3fc3b22529a775d1594ae2dd819278b

patches:
  - path: patch-loadbalancer-ips.yaml
  - path: patch-ingress-cert-host.yaml
  - path: patch-backend-deployment.yaml
  - path: patch-backend-migrate-deployment.yaml
  - path: patch-batch-env.yaml
  - path: patch-frontend-deployment.yaml
