apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: price-monitoring-production

images:
  - name: docker-registry.kuroweb.net/price-monitoring-backend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-production
    newTag: b4cbd706ba1c1e4e76298a0deed7456a0c9c758b
  - name: docker-registry.kuroweb.net/price-monitoring-backend-playwright:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-playwright-production
    newTag: f75964372d261cabba6ed72960161bcf6ec1a306
  - name: docker-registry.kuroweb.net/price-monitoring-backend-camoufox:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-camoufox-production
    newTag: 2de9f7e6286a22b8f0a476c3696c57783f6ea6c0
  - name: docker-registry.kuroweb.net/price-monitoring-frontend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-frontend-production
    newTag: cd9b4011b86f9d9318dc7c61b09476d0c66810e9

patches:
  - path: patches/backend.yaml
  - path: patches/backend-db.yaml
  - path: patches/backend-redis.yaml
  - path: patches/backend-playwright.yaml
  - path: patches/backend-camoufox.yaml
  - path: patches/backend-migrate.yaml
  - path: patches/backend-batch-1.yaml
  - path: patches/backend-batch-2.yaml
  - path: patches/backend-batch-3.yaml
  - path: patches/backend-batch-4.yaml
  - path: patches/frontend.yaml
  - path: patches/web-ingress.yaml
