apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: price-monitoring-production

images:
  - name: docker-registry.kuroweb.net/price-monitoring-backend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-production
    newTag: 444e650fe3fc3b22529a775d1594ae2dd819278b
  - name: docker-registry.kuroweb.net/price-monitoring-backend-playwright:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-playwright-production
    newTag: 444e650fe3fc3b22529a775d1594ae2dd819278b
  - name: docker-registry.kuroweb.net/price-monitoring-frontend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-frontend-production
    newTag: 444e650fe3fc3b22529a775d1594ae2dd819278b

patches:
  - path: patches/backend.yaml
  - path: patches/backend-db.yaml
  - path: patches/backend-redis.yaml
  - path: patches/backend-playwright.yaml
  - path: patches/backend-migrate.yaml
  - path: patches/backend-batch-1.yaml
  - path: patches/backend-batch-2.yaml
  - path: patches/backend-batch-3.yaml
  - path: patches/backend-batch-4.yaml
  - path: patches/frontend.yaml
  - path: patches/web-ingress.yaml
