apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-camoufox-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend-camoufox
          resources:
            limits:
              cpu: "300m"
