apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-batch-3-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend-batch-3
          command: ["sidekiq", "-C", "config/sidekiq/crawl_process_2.yml", "-e", "integration"]
          env:
            - name: ALLOWED_ORIGINS
              value: "10.15.100.221"
            - name: DD_SERVICE
              value: "price-monitoring-integration"
            - name: DD_ENV
              value: "integration"
