apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-playwright-deployment
spec:
  replicas: 10
  template:
    spec:
      containers:
        - name: backend-playwright
          resources:
            limits:
              cpu: "700m"
              memory: "1200Mi"
