apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-camoufox-deployment
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: backend-camoufox
          resources:
            limits:
              cpu: "700m"
              memory: "1000Mi"
