apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-batch-2-deployment
spec:
  template:
    spec:
      containers:
        - name: backend-batch-2
          command: ["sidekiq", "-C", "config/sidekiq/general_process.yml", "-e", "production"]
          env:
            - name: ALLOWED_ORIGINS
              value: "10.15.100.211"
            - name: DD_SERVICE
              value: "price-monitoring"
            - name: DD_ENV
              value: "production"
