apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  sources:
    - repoURL: https://helm.datadoghq.com
      chart: datadog-operator
      targetRevision: 1.2.0
    - repoURL: https://github.com/kuroweb/k8s
      path: manifests/datadog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
