apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    site: ap1.datadoghq.com
    kubelet:
      tlsVerify: false
    tags:
      - env: production
      - service: price-monitoring
      - version: v1.0.0
