apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog-agent
  namespace: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    site: ap1.datadoghq.com
    kubelet:
      tlsVerify: false
    tags:
      - "env:integration"
      - "service:my-service"
      - "version:v1.0.0"
