apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: auth-provider-integration

images:
  - name: docker-registry.kuroweb.net/auth-provider-backend:placeholder
    newName: docker-registry.kuroweb.net/auth-provider-backend-integration
    newTag: b1224608826bae96a36fb9c00ae37678c709fe8c

patches:
  - path: patches/backend.yaml
  - path: patches/backend-db.yaml
  - path: patches/backend-redis.yaml
  - path: patches/backend-migrate.yaml
  - path: patches/ingress.yaml
