apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-migrate-deployment
spec:
  template:
    spec:
      containers:
        - name: backend-migrate
          command:
            [
              "/bin/sh",
              "-c",
              "RAILS_ENV=integration rails db:create && RAILS_ENV=integration rails db:migrate && ./bin/rails server -b 0.0.0.0 -p 3000 -e integration",
            ]
          env:
            - name: ALLOWED_ORIGINS
              value: "10.15.100.234,integration.auth-provider.kuroweb.net,www.integration.auth-provider.kuroweb.net,backend-service"
            - name: DOMAIN_NAME
              value: "integration.auth-provider.kuroweb.net"
            - name: DD_SERVICE
              value: "auth-provider-integration"
            - name: DD_ENV
              value: "integration"
